services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Welcome@2024"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql    
  redis:
    image: redis:latest
    ports:
      - redis-data:/data
volumes:
  redis-data:
  sql-data:          